### ISSUE TITLE
Waiting...

### ISSUE THREAD

**Issue by ghost** [hrichharms/IsAiming#1]
I'm waiting 🙂

**Comment by hrichharms** [comment]
what for?

**Comment by ghost** [comment]
to do neural network stuff with it

**Comment by hrichharms** [comment]
you can help by contributing training data :)

**Comment by ghost** [comment]
add me on discord Hafez#0877

**Comment by hrichharms** [comment]
not working, r u missing a digit on the end?

mine: Heinrich#2101

**Comment by ghost** [comment]
Added u
